-- Copyright (c) 2003, 2020, Oracle and/or its affiliates. All rights reserved.
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License, version 2.0,
-- as published by the Free Software Foundation.
--
-- This program is also distributed with certain software (including
-- but not limited to OpenSSL) that is licensed under separate terms,
-- as designated in a particular file or component or in included license
-- documentation.  The authors of MySQL hereby grant you an additional
-- permission to link the program and your derivative works with the
-- separately licensed software that they have included with MySQL.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License, version 2.0, for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program; if not, write to the Free Software
-- Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA


-- DO NOT EDIT THIS FILE. It is generated automatically by the MySQL
-- documentation team. If you require changes to the content of this
-- file, contact the documentation team.

-- File generation date: 2020-03-06
-- MySQL series: 8.0
-- Document repository revision: 65252

-- To use this file, load its contents into the mysql system database.
-- For example, with the mysql client program, process the file like
-- this, where file_name is the name of this file:

--     mysql -u root -p mysql < file_name

SET sql_log_bin=0;
SET NAMES 'utf8';

TRUNCATE TABLE help_topic;
TRUNCATE TABLE help_category;
TRUNCATE TABLE help_keyword;
TRUNCATE TABLE help_relation;

START TRANSACTION;

INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (0,'Contents',0,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (1,'Help Metadata',0,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (2,'Data Types',0,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (3,'Administration',0,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (4,'Language Structure',0,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (5,'Geographic Features',0,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (6,'MBR',5,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (7,'WKT',5,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (8,'Functions',0,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (9,'Comparison Operators',8,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (10,'Logical Operators',8,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (11,'Control Flow Functions',8,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (12,'Numeric Functions',8,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (13,'Date and Time Functions',8,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (14,'String Functions',8,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (15,'Bit Functions',8,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (16,'Encryption Functions',8,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (17,'Locking Functions',8,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (18,'Information Functions',8,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (19,'Spatial Functions',8,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (20,'WKT Functions',19,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (21,'WKB Functions',19,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (22,'Geometry Constructors',19,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (23,'Geometry Property Functions',19,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (24,'Point Property Functions',19,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (25,'LineString Property Functions',19,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (26,'Polygon Property Functions',19,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (27,'GeometryCollection Property Functions',19,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (28,'Geometry Relation Functions',19,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (29,'MBR Functions',19,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (30,'GROUP BY Functions and Modifiers',8,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (31,'Performance Schema Functions',8,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (32,'Miscellaneous Functions',8,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (33,'Data Definition',0,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (34,'Data Manipulation',0,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (35,'Transactions',0,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (36,'Compound Statements',0,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (37,'Account Management',0,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (38,'Table Maintenance',0,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (39,'User-Defined Functions',0,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (40,'Components',0,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (41,'Plugins',0,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (42,'Utility',0,'');
INSERT INTO help_category (help_category_id,name,parent_category_id,url) VALUES (43,'Storage Engines',0,'');


COMMIT;

